/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.Model_HD3;
import javax.security.auth.callback.ConfirmationCallback;
import javax.swing.JOptionPane;
import repositories.Repositories_HD3;

/**
 *
 * @author Chi Dat
 */
public class View_HD3 extends javax.swing.JFrame {
    private Repositories_HD3 rp_HD3 = new Repositories_HD3();
    

    /**
     * Creates new form View_HD3
     */
    public View_HD3() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_MaHD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_MaKH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_SoDienThoai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_DiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_TienCoc = new javax.swing.JTextField();
        btn_HoaDon = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_CheckTTKH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Mã HD:");

        jLabel2.setText("Mã NV:");

        jLabel3.setText("Mã KH:");

        jLabel4.setText("SĐT:");

        jLabel5.setText("Địa Chỉ:");

        jLabel6.setText("Tiền Cọc:");

        btn_HoaDon.setBackground(new java.awt.Color(204, 255, 255));
        btn_HoaDon.setText("Tạo Hóa Đơn");
        btn_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HoaDonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("THÔNG TIN HÓA ĐƠN CHỜ");

        btn_CheckTTKH.setBackground(new java.awt.Color(204, 255, 255));
        btn_CheckTTKH.setText("Check Thông Tin Khách Hàng");
        btn_CheckTTKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckTTKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(74, 74, 74)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_SoDienThoai)
                                    .addComponent(txt_DiaChi)
                                    .addComponent(txt_TienCoc)
                                    .addComponent(txt_MaKH)
                                    .addComponent(txt_MaNV)
                                    .addComponent(txt_MaHD)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(btn_HoaDon)))
                .addGap(227, 227, 227))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_CheckTTKH)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_TienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btn_CheckTTKH)
                .addGap(7, 7, 7)
                .addComponent(btn_HoaDon)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HoaDonActionPerformed
        // TODO add your handling code here:
        
        if(this.readForm_HD3()!= null){
            if(rp_HD3.checkTung_HD3(txt_MaHD.getText())!= null){
                JOptionPane.showMessageDialog(this, "Mã Hóa Đơn đã tồn tại");
            }
        }else{
            if(rp_HD3.them_HD3(this.readForm_HD3())>0){
                JOptionPane.showMessageDialog(this, "Tạo hóa đơn thành công");
            }else{
                JOptionPane.showMessageDialog(this, "Tạo hóa đơn thất bại");
            }
        }
    
    }//GEN-LAST:event_btn_HoaDonActionPerformed

    private void btn_CheckTTKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckTTKHActionPerformed
        // TODO add your handling code here:
        View_QLKH kh = new View_QLKH();
        kh.setVisible(true);
    }//GEN-LAST:event_btn_CheckTTKHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_HD3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_HD3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_HD3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_HD3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_HD3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CheckTTKH;
    private javax.swing.JButton btn_HoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_MaHD;
    private javax.swing.JTextField txt_MaKH;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_SoDienThoai;
    private javax.swing.JTextField txt_TienCoc;
    // End of variables declaration//GEN-END:variables
private Model_HD3 readForm_HD3(){
    String maHD;
    String maNV;
    String maKH;
    String soDienThoai;
    String diaChi;
    double tienCoc;
    
    maHD = txt_MaHD.getText().trim();
    if(maHD.isEmpty()){
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã hóa đơn");
        txt_MaHD.requestFocus();
        return null;
    }
    maNV = txt_MaNV.getText().trim();
    if(maNV.isEmpty()){
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã nhân viên");
        txt_MaNV.requestFocus();
        return null;
    }
    maKH = txt_MaKH.getText().trim();
    if(maKH.isEmpty()){
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã khách hàng");
        txt_MaKH.requestFocus();
        return null;
              
    }
    soDienThoai = txt_SoDienThoai.getText().trim();
    if(soDienThoai.isEmpty()){
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập số điện thoại");
        txt_SoDienThoai.requestFocus();
        return null;
    }
    diaChi = txt_DiaChi.getText().trim();
    if(diaChi.isEmpty()){
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập địa chỉ");
        txt_DiaChi.requestFocus();
        return null;
                
    }
    
    try {
        tienCoc = Double.parseDouble(txt_TienCoc.getText());
        if(tienCoc < 0){
            JOptionPane.showMessageDialog(this, "tiền cọc không hợp lệ");
            txt_TienCoc.requestFocus();
            return null;
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Tiền cọc phải là số");
        txt_TienCoc.requestFocus();
        return null;
    }
    
    return new Model_HD3(maHD, maNV, maKH, soDienThoai, diaChi, tienCoc);
    
}
}
