/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultTreeSelectionModel;
import model.Model_KM;
import repositories.Repositories_KM;
import java.util.regex.Pattern;
import java.util.regex.Matcher;

/**
 *
 * @author rinbo
 */
public class View_KM extends javax.swing.JFrame {

    private repositories.Repositories_KM rp = new Repositories_KM();
    private DefaultTableModel mol = new DefaultTableModel();
    private int i = -1;

    /**
     * Creates new form View_KM
     */
    public View_KM() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.fillTable(rp.getAll_KM());
        i = rp.getAll_KM().size();
        this.showDaTa(i - 1);
        tbl_KM.setRowSelectionInterval(i - 1, i - 1);
    }

    private void fillTable(ArrayList<model.Model_KM> list) {
        mol = (DefaultTableModel) tbl_KM.getModel();
        mol.setRowCount(0);
        for (Model_KM x : list) {
            mol.addRow(x.toDaTaRow_KM());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_MaKM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_TenKM = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_MT = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_PTGG = new javax.swing.JTextField();
        tbn_Them = new javax.swing.JButton();
        tbn_Sua = new javax.swing.JButton();
        tbn_Xoa = new javax.swing.JButton();
        tbn_Cancel = new javax.swing.JButton();
        tbn_Reset = new javax.swing.JButton();
        jdc_NBD = new com.toedter.calendar.JDateChooser();
        jdc_NKT = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        txt_timkiem = new javax.swing.JTextField();
        tbn_TK = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_KM = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jdc_NBDTK = new com.toedter.calendar.JDateChooser();
        jdc_NKTTK = new com.toedter.calendar.JDateChooser();
        tbl_TKTN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Mã Khuyến Mại:");

        jLabel2.setText("Tên Khuyến Mại:");

        jLabel3.setText("Mô Tả:");

        txt_MT.setColumns(20);
        txt_MT.setRows(5);
        jScrollPane1.setViewportView(txt_MT);

        jLabel4.setText("Ngày Bắt Đầu:");

        jLabel5.setText("Ngày Kết Thúc:");

        jLabel6.setText("Phần Trăm Giảm Giá:");

        tbn_Them.setText("Thêm");
        tbn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_ThemActionPerformed(evt);
            }
        });

        tbn_Sua.setText("Sửa");
        tbn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_SuaActionPerformed(evt);
            }
        });

        tbn_Xoa.setText("Xóa");
        tbn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_XoaActionPerformed(evt);
            }
        });

        tbn_Cancel.setText("Cancel");
        tbn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_CancelActionPerformed(evt);
            }
        });

        tbn_Reset.setText("Reset");
        tbn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_ResetActionPerformed(evt);
            }
        });

        jdc_NBD.setDateFormatString("yyyy-MM-dd");

        jdc_NKT.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_MaKM, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(txt_TenKM))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tbn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(tbn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(tbn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(tbn_Cancel)
                                .addGap(78, 78, 78))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_PTGG, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jdc_NKT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(jdc_NBD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_MaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4))
                    .addComponent(jdc_NBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_TenKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jdc_NKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txt_PTGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbn_Xoa)
                            .addComponent(tbn_Sua)
                            .addComponent(tbn_Them))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbn_Cancel)
                            .addComponent(tbn_Reset))
                        .addGap(94, 94, 94))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 102));

        tbn_TK.setText("Tìm Kiếm");
        tbn_TK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_TKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbn_TK))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tbn_TK)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(txt_timkiem))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(51, 255, 51));

        tbl_KM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Giảm Giá", "Tên Giảm Giá", "Phần Trăm Giảm Giá", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Mô Tả"
            }
        ));
        tbl_KM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KMMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_KM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setText("Quản Lý Khuyến Mại");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("tìm kiếm theo thời gian"));

        jdc_NBDTK.setDateFormatString("yyyy-MM-dd");

        jdc_NKTTK.setDateFormatString("yyyy-MM-dd");

        tbl_TKTN.setText("Tìm Kiếm");
        tbl_TKTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl_TKTNActionPerformed(evt);
            }
        });

        jLabel8.setText("Ngày Bắt Đầu:");

        jLabel9.setText("Ngày Kết Thúc:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdc_NKTTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdc_NBDTK, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbl_TKTN)
                .addGap(66, 66, 66))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdc_NBDTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdc_NKTTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbl_TKTN)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_KMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KMMouseClicked
        // TODO add your handling code here:
        i = tbl_KM.getSelectedRow();
        this.showDaTa(i);
        txt_MaKM.disable();
    }//GEN-LAST:event_tbl_KMMouseClicked

    private void tbn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_ThemActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(this, "bạn có muốn thêm khuyến mại không");
        if (chon == 0) {
            if (this.readForm() != null) {
                if (rp.checkTrung_KM(txt_MaKM.getText()) != null) {
                    JOptionPane.showMessageDialog(this, "trùng mã");
                } else {
                    if (rp.them_KM(readForm()) > 0) {
                        JOptionPane.showMessageDialog(this, "thêm thành công");
                        this.fillTable(rp.getAll_KM());
                    } else {
                        JOptionPane.showMessageDialog(this, "thêm thất bại ");

                    }
                }

            }
        }
        /*if (chon == 0) {
            if (this.readForm() != null) {
                i = tbl_KM.getSelectedRow();
                String ma = tbl_KM.getValueAt(i, 0).toString();
                if (rp.checkTrung_KM(ma) != null) {
                    JOptionPane.showMessageDialog(this, "Mã đã tồn tại");
                    txt_MaKM.requestFocus();
                } else {
                    if (rp.them_KM(this.readForm()) > 0) {
                        JOptionPane.showMessageDialog(this, "thêm thành công");
                        this.fillTable(rp.getAll_KM());
                    } else {
                        JOptionPane.showMessageDialog(this, "thêm thất bại");
                    }
                }

            }
        }*/

    }//GEN-LAST:event_tbn_ThemActionPerformed

    private void tbn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_SuaActionPerformed
        // TODO add your handling code here:
        i = tbl_KM.getSelectedRow();
        int chon = JOptionPane.showConfirmDialog(this, "bạn có muốn sửa không?");
        if (chon == 0) {
            if (i == -1) {
                JOptionPane.showMessageDialog(this, "bạn chưa chọn dòng dữ liệu muốn sửa");
            } else {
                if (this.readForm() != null) {
                    String maKH = tbl_KM.getValueAt(i, 0).toString();
                    if (rp.sua_KM(maKH, this.readForm()) > 0) {
                        JOptionPane.showMessageDialog(this, "sửa thành công");
                        this.fillTable(rp.getAll_KM());
                    } else {
                        JOptionPane.showMessageDialog(this, "sửa thất bại");
                    }
                }
            }
        }
    }//GEN-LAST:event_tbn_SuaActionPerformed

    private void tbn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_XoaActionPerformed
        // TODO add your handling code here:
        i = tbl_KM.getSelectedRow();
        int chon = JOptionPane.showConfirmDialog(this, "bạn có muốn xóa dữ liệu này không?");
        if (chon == 0) {
            if (i == -1) {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn dữ liệu muốn xóa");
            } else {
                if (this.readForm() != null) {
                    String maKM = tbl_KM.getValueAt(i, 0).toString();
                    if (rp.xoa_KM(maKM) > 0) {
                        JOptionPane.showMessageDialog(this, "xóa thành công");
                        this.fillTable(rp.getAll_KM());
                    } else {
                        JOptionPane.showMessageDialog(this, "xóa thất bại");
                    }
                }
            }
        }
    }//GEN-LAST:event_tbn_XoaActionPerformed

    private void tbn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_ResetActionPerformed
        // TODO add your handling code here:
        txt_MaKM.setText("");
        txt_TenKM.setText("");
        txt_PTGG.setText("");
        jdc_NBD.setDate(null);
        jdc_NKT.setDate(null);
        txt_MT.setText("");
        txt_timkiem.setText("");
        txt_MaKM.setEnabled(true);
        this.fillTable(rp.getAll_KM());

    }//GEN-LAST:event_tbn_ResetActionPerformed

    private void tbn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_CancelActionPerformed
        // TODO add your handling code here:
        View_TrangChu TC = new View_TrangChu();
        TC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tbn_CancelActionPerformed

    private void tbn_TKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_TKActionPerformed
        // TODO add your handling code here:
        String maTK = txt_timkiem.getText().trim();
        if (maTK.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập thong tin tìm kiếm");
        } else {
            ArrayList<Model_KM> KQTK = rp.timKiem_KM(maTK);
            if (KQTK.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Mã không tồn tại");
            } else {

                JOptionPane.showMessageDialog(this, "đã thấy dữ liệu");
                this.fillTable(KQTK);
            }
        }
    }//GEN-LAST:event_tbn_TKActionPerformed

    private void tbl_TKTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl_TKTNActionPerformed
        // TODO add your handling code here:
        Date ngayStar = jdc_NBDTK.getDate();
        Date ngayEnd = jdc_NKTTK.getDate();
        if (ngayStar.after(ngayEnd)) {
            JOptionPane.showMessageDialog(this, "dữ liệu không hợp lệ");
        }else{
            if (ngayEnd == null || ngayStar == null) {
            JOptionPane.showMessageDialog(this, "bạn chưa điền đủ thông tin ngày bắt đầu hoặc ngày kết thúc! vui lòng kiểm tra lại");
        }else{
            ArrayList<Model_KM> KQTKTTG = rp.timKiem_KMTKTG(ngayStar, ngayEnd);
            if (KQTKTTG.isEmpty()) {
                JOptionPane.showMessageDialog(this, "không có khuyến mại nào trong khoảng thời gian này");
            }else{
                JOptionPane.showMessageDialog(this, "Đã tìm thấy dữ liệu");
                this.fillTable(KQTKTTG);
            }
        }
        }
        
    }//GEN-LAST:event_tbl_TKTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_KM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_KM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_KM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_KM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_KM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdc_NBD;
    private com.toedter.calendar.JDateChooser jdc_NBDTK;
    private com.toedter.calendar.JDateChooser jdc_NKT;
    private com.toedter.calendar.JDateChooser jdc_NKTTK;
    private javax.swing.JTable tbl_KM;
    private javax.swing.JButton tbl_TKTN;
    private javax.swing.JButton tbn_Cancel;
    private javax.swing.JButton tbn_Reset;
    private javax.swing.JButton tbn_Sua;
    private javax.swing.JButton tbn_TK;
    private javax.swing.JButton tbn_Them;
    private javax.swing.JButton tbn_Xoa;
    private javax.swing.JTextArea txt_MT;
    private javax.swing.JTextField txt_MaKM;
    private javax.swing.JTextField txt_PTGG;
    private javax.swing.JTextField txt_TenKM;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
    private void showDaTa(int i) {
        txt_MaKM.setText(tbl_KM.getValueAt(i, 0).toString());
        txt_TenKM.setText(tbl_KM.getValueAt(i, 1).toString());
        txt_PTGG.setText(tbl_KM.getValueAt(i, 2).toString());
        try {
            Date ngayBD = new SimpleDateFormat("yyyy-MM-dd").parse(tbl_KM.getValueAt(i, 3).toString());
            jdc_NBD.setDate(ngayBD);
        } catch (Exception e) {
            e.printStackTrace();

        }
        try {
            Date ngayKT = new SimpleDateFormat("yyyy-MM-dd").parse(tbl_KM.getValueAt(i, 4).toString());
            jdc_NKT.setDate(ngayKT);
        } catch (Exception e) {
            e.printStackTrace();
        }
        txt_MT.setText(tbl_KM.getValueAt(i, 5).toString());

    }

    private Model_KM readForm() {
        String maKM = txt_MaKM.getText().trim();
        if (maKM.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập mã khuyến mại");
            txt_MaKM.requestFocus();
            return null;
        }
        String tenKM = txt_TenKM.getText().trim();
        if (tenKM.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập tên khuyến mại");
            txt_TenKM.requestFocus();
            return null;
        }

        String checkPTGG = txt_PTGG.getText().trim();
        double pTGG;

        if (checkPTGG.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập số phần trăm giảm giá");
            txt_PTGG.requestFocus();
            return null;
        } else {
            try {
                pTGG = Double.parseDouble(checkPTGG);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "nhập sai định dạng phần trăm giảm giá");
                txt_PTGG.requestFocus();
                return null;
            }
        }
        Date ngayBD = jdc_NBD.getDate();
        if (ngayBD == null) {
            JOptionPane.showMessageDialog(this, "bạn chưa chọn ngày bắt đầu");
            jdc_NBD.requestFocus();
            return null;
        }

        Date ngayKT = jdc_NKT.getDate();
        if (ngayKT == null) {
            JOptionPane.showMessageDialog(this, "bạn chưa chọn ngày kết thúc");
            jdc_NKT.requestFocus();
            return null;
        }
        if (ngayBD.after(ngayKT)) {
            JOptionPane.showMessageDialog(this, "dữ liệu không hợp lệ! ngày bắt đầu phải trước ngày kết thúc");
            jdc_NBD.requestFocus();
            return null;
        }

        String moTa = txt_MT.getText().trim();
        if (moTa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bạn chưa nhập mô tả khuyến mại");
            txt_MaKM.requestFocus();
            return null;
        }
        return new Model_KM(maKM, tenKM, pTGG, ngayBD, ngayKT, moTa);
    }
}
